"""Константы проекта."""

MAX_NAME_LENGTH: int = 256
MAX_SLUG_LENGTH: int = 256
MAX_UNIT_LENGTH: int = 256
MAX_INGREDIENT_AMOUNT: int = 100_000
MIN_INGREDIENT_AMOUNT: int = 1
MAX_COOKING_TIME: int = 100_000
MIN_COOKING_TIME: int = 1
