# Generated by Django 3.2.3 on 2024-08-16 16:03

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator, users.validators.validate_username], verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator, users.validators.validate_email], verbose_name='Емайл')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator], verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator], verbose_name='Фамилия')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator, users.validators.MaxLengthPasswordValidator], verbose_name='Пароль')),
                ('avatar', models.ImageField(blank=True, default='users/default.png', upload_to='users/', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=5, validators=[django.core.validators.MaxLengthValidator], verbose_name='Роль')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe', verbose_name='Избранное')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('shopping_cart', models.ManyToManyField(blank=True, related_name='shopping_cart', to='recipes.Recipe', verbose_name='Список покупок')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='_users_userwithsubscriptions_subscriptions_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
